POST http://localhost:8080/accounts
Content-Type: application/json

{
  "Owner": "yffdim",
  "Balance": 1000,
  "Currency": "EUR"
}

###
GET http://localhost:8080/accounts/100

###
GET http://localhost:8080/accounts?page_id=1&page_size=5

###
POST http://localhost:8080/transfer
Content-Type: application/json

{
  "from_account_id": 1,
  "to_account_id": 3,
  "amount": 10,
  "currency": "USD"
}


###
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "NhatLe",
  "password": "123456",
  "fullname": "Le Van Nhat",
  "email": "nhat1952001@gmail.com"
}